osism/documentation

source/operations/services/neutron.rst
=> added neutron agent delete

source/operations/services/nova.rst
=> added compute service delete

source/configuration/kolla/nova.rst
modified nova configuration for pci passthrough
=> modified nova configuration for pci passthrough

source/configuration/kolla/nova.rst
=> only few typos

source/operations/services/mariadb.rst
added mariadb binary logs days configuration and purge the binary logs
=> added mariadb binary logs days configuration and purge the binary logs

source/operations/services/mariadb.rst
added howto shrink table django_session in horizon database
=> added howto shrink table django_session in horizon database

source/operations/services/mariadb.rst
fixed expire_logs_days_logs_days to expire_logs_days
=> fixed expire_logs_days_logs_days to expire_logs_days

source/configuration/kolla/nova.rst
description of IOMMU PASS and WARN
=> description of IOMMU PASS and WARN

source/configuration/environments/kolla/nova.rst
getting id of gpu via lspci before editing vfio module configuration
=> moved lspci output for getting id for gpu

source/operations/nova.rst
some databases and tables for searching old compute nodes entries with examples and SQL queries
=> added some databases and tables to search for deleting old compute nodes

source/operations/ceph.rst
changed howto replace a defect ceph osd
=> changed replace defect osd

source/operations/ceph.rst
=> added howto repair ceph pg

source/configuration/cookiecutter.rst, source/configuration/update.rst, source/deployment/manager.rst
* configuration/cookiecutter
* configuration/update
* deployment/manager
=> Enhance documentation for

source/deployment/provisioning.rst
moved swap partition for a better overview
=> moved swap partition for a better overview

source/deployment/services/ceph.rst
=> typo in ceph-mgr description

source/upgrade/kolla.rst
specified secrets file for adding redis between ocata and pike
=> specified secrets file for adding redis between ocata and pike

source/operations/aptly.rst
changed format of code section, added repositories data
=> changed format of code section, added repositories data

source/operations.rst, source/operations/prometheus.rst
prometheus in start loop with panic message
panic: runtime error: slice bounds out of range
solution, delete old data in
/var/lib/docker/volumes/prometheus_prometheus/_data
=> added prometheus message for start loop

source/operations/aptly.rst
added additional repositories components, restricted universe multiverse
=> added additional repositories components, restricted universe multiverse

source/notes/openstack.rst
cleanup those messages
Instance <instanceID> has allocations against this compute host but is not found in the database.
=> howto cleanup allocations against messages

source/notes/openstack.rst
added second solution for rpc version cap error
=> added second solution for rpc version cap error

source/configuration/environments/openstack.rst, source/deployment/services/infrastructure.rst
added link to self signed certification creation for haproxy
reference for better deployment workflow
=> added link to self signed certification creation for haproxy

source/operations/mariadb.rst, source/upgrade/kolla.rst, source/upgrade/manager.rst
- Make chapter headings upper case
- Fix reference links
- Rearrange order in manager chapter
=> Revise upgrade chapter

source/upgrade/kolla.rst
- Add Docker commands on how to remove glance-registry
=> Upgrade: How to remove glance-registry

source/upgrade/kolla.rst
Describe how to remove old versions of Docker images.
=> Upgrade: Remove old Docker images

source/operations/nova.rst
added howto use the ssh via nova_ssh for copying e.g. instance images
=> added howto use the ssh via nova_ssh for copying e.g. instance images

source/deployment/services/openstack.rst
=> openstack: deploy placement service

source/operations/panko.rst
Add some documentation about even_time_to_live and how to add a cronjob to delete expired Panko events
=> Document panko-expirer configuration (event_time_to_live)

source/configuration/cookiecutter.rst, source/configuration/environments/ceph.rst, source/configuration/environments/infrastructure/mirror.rst, source/deployment/services/loadbalancer.rst, source/operations/ceph.rst, source/operations/mariadb.rst
luminous -> nautilus
rocky -> train
=> Fix some versions

.github/workflows/sphinx.yml
=> github: add sphinx workflow

requirements.txt
=> Pin python requirements

.github/workflows/broken-link-check.yml
=> github: add 'Broken link check' workflow

source/deployment/services/ceph.rst
=> added missing slash

source/appendix/tables/service-networks.rst
=> appendix: add ucs service network

.github/renovate.json
=> renovate: add commitBody

.github/pr-labeler.yml
=> github: add renovate to pr-labeler config

source/appendix/tables/service-networks.rst
=> appendix: add keycloak service network

source/configuration/environments/openstack/nova.rst
edited the pci pass through doings for also using customer gpu
=> some more details for gpu pci pass through

source/operations/cinder.rst
=> operations/cinder: There are still untyped volumes unmigrated

source/operations/nova.rst
=> operations/nova: add "Row size too large"

source/operations/nova.rst
=> operations/nova: Host '<hostname>' is not mapped to any cell

source/operations/ceph.rst
=> operations/ceph: 3 monitors have not enabled msgr2

source/operations.rst, source/operations/ubuntu.rst
=> operations: add ubuntu

source/deployment/services/ceph.rst
=> added information about using multipath for ceph

source/deployment/services/ceph.rst, source/deployment/services/openstack.rst, source/test/benchmark/rally.rst
=> changed helper calls and added a fixme to rally

source/test/openstack.rst
=> added some tests for openstack services

source/deployment/provisioning.rst
=> 2021, new link to preseed or autoinstall isos

source/deployment/services/loadbalancer.rst
=> Update octavia documentation to fit >= Train release

source/notes/openstack.rst
=> add openstack client placement cli commands

source/operations/elasticsearch.rst
=> add verbose curl call for elasticsearch in operations

source/deployment/services/loadbalancer.rst
=> Loadbalancer: Fix IP for health manager iface on control node

source/overview.rst, source/overview/cli-reference.rst
=> added cli reference, added newline

source/appendix/tables/service-networks.rst
=> appendix: add netbox network

source/appendix/tables/service-networks.rst
=> appendix: add health monitor network

source/overview/requirements.rst
=> Only support ubuntu 20.04

source/deployment/services/loadbalancer.rst
=> Deployment Octavia: add config options necessary for victoria

source/appendix/tables/service-networks.rst, source/appendix/tables/webinterfaces.rst
=> Add rundeck port + network

source/appendix/tables/webinterfaces.rst
=> Add patchman webinterface

source/appendix/tables/service-networks.rst, source/appendix/tables/webinterfaces.rst
=> Add heimdall network and webinterface

source/conf.py
=> Remove custom.css

source/appendix/tables/webinterfaces.rst
=> Remove dups from webinterfaces table

source/appendix/tables/service-networks.rst, source/appendix/tables/webinterfaces.rst
=> appendix: add jenkins networks & jenkins/netbox webinterfaces

source/overview.rst, source/overview/secrets.rst
=> add information about ansible-vault and secret.yml files

source/operations/rabbitmq.rst, source/test/infrastructure.rst
=> add new rabbitmq cluster status output

source/configuration/environments/generic/docker.rst, source/operations/docker.rst
=> add information about docker pin/hold

source/overview/requirements.rst
=> add necessary basic knowledge, #209

source/appendix/tables/service-networks.rst
Signed-off-by: Ferenc Géczi <geczi@univention.de>
=> feat(openldap): Add OpenLDAP network

source/operations/placement.rst
=> add resource provider list

source/configuration/environments/openstack/cinder.rst
=> add cinder backend lvm configuration

.github/workflows/build-documentation.yml
=> github: use SamKirkland/FTP-Deploy-Action

.github/workflows/build-documentation.yml
=> github: fix wrong local-dir

.github/workflows/build-documentation.yml
=> github: fix wrong server-dir

.github/workflows/build-documentation.yml, source/conf.py
=> master -> main

source/deployment/provisioning.rst
=> changed lv partition size for tmp

.github/workflows/build-documentation.yml
=> github: add workflow_dispatch

source/index.rst
=> osism.de -> osism.tech

source/appendix/tables/webinterfaces.rst
=> appendix: add missing webinterfaces & fix rally port

source/appendix/tables/service-networks.rst
Signed-off-by: Ferenc Géczi <geczi@univention.de>
=> Remove UCS

source/appendix/tables/service-networks.rst
=> appendix: add virtualbmc service network

source/configuration/cookiecutter.rst
=> Update python dependency list for cookiecutter installation

source/deployment/services/infrastructure.rst
=> Describe how to login to kibana dashboard

source/appendix/tables/webinterfaces.rst
=> Fix ceph dashboard in webinterfaces table

source/deployment/services/ceph.rst
=> Add ceph-crash daemon playbook to ceph deployment

source/operations/ceph.rst
=> Check if it is safe to remove ceph osd

.github/workflows/build-documentation.yml
=> github: ignore the reference directory

source/deployment/provisioning.rst
=> Use minio.services.osism.tech

source/appendix/tables/service-networks.rst
=> appendix: update service networks

source/deployment/services/openstack.rst
=> Add 'ovn' to list of osism-kolla deploy steps

source/deployment/services/openstack.rst
=> move ovn in deployment section to networking

source/configuration/networks.rst, source/deployment/manager.rst
=> some inventory host_vars example for network IP configuration

source/operations/rabbitmq.rst
=> rabbitmq erlang cookie error handling

source/appendix/tables/webinterfaces.rst, source/deployment/services/ceph.rst
- enable http Ceph dashboard
- create the admin user for the dashboard
=> Describe how to enable the Ceph dashboard

.github/workflows/build-documentation.yml
=> github: fix build workflow

.github/workflows/build-documentation.yml
Reference to solution: https://github.com/SamKirkland/FTP-Deploy-Action/pull/205
=> resolved build error

source/appendix/tables/service-networks.rst
=> appendix: add traefik network

source/operations/openstack.rst
=> operations/openstack: Show all running instances

source/appendix/tables/service-networks.rst
=> appendix: add atlantis service network

.github/workflows/build-documentation.yml
partly: osism/issues#85
Signed-off-by: Ramona Rautenberg <rautenberg@osism.tech>
=> github: run branch builds on main only

source/appendix/tables/service-networks.rst
=> appendix: add dnsdist service network

source/configuration.rst, source/configuration/proxy.rst
=> add proxy configuration

source/appendix/tables/service-networks.rst
=> appendix: add zuul service network

source/configuration/environments/generic.rst, source/configuration/environments/generic/chrony.rst, source/test/generic.rst
=> add chronyd command for checking ntp service, add chrony configuration

source/test/ceph.rst
=> add some more ceph commands for testing

source/appendix/tables/webinterfaces.rst
=> appendix: add vault service port & fix cgit service port

source/development.rst, source/development/new_service.rst
=> Added tutorial: How to add a service to osism

source/configuration/environments/openstack.rst
=> add howto add certificates into containers

.github/renovate.json
=> Change sign-off address from Renovate Bot

source/appendix/tables/webinterfaces.rst
=> Add webinterface documentation for RabbitMQ

source/appendix/tables/service-networks.rst
=> appendix: resize the manager network

source/appendix/tables/webinterfaces.rst, source/configuration/networks.rst, source/deployment/services.rst, source/deployment/services/monitoring.rst
=> Add Prometheus/Grafana based monitoring documentation

source/overview/cli-reference.rst
=> update OSISM cli reference

source/deployment/services/infrastructure.rst, source/deployment/services/loadbalancer.rst, source/deployment/services/openstack.rst, source/operations/haproxy.rst, source/scaling/control.rst, source/upgrade/kolla.rst
=> Change `haproxy` deploy commands to `loadbalancer`

source/overview/service-architecture.rst
=> overview: revisit the service-architecture

source/overview/secrets.rst
closes https://github.com/osism/issues/issues/145
=> removed secrets search documenation as it was never implemented

source/configuration/environments/openstack/nova.rst
Fixes: #356
Signed-off-by: Ralf Heiringhoff <ralf.heiringhoff@plusserver.com>
=> remove potential harmful config that could leak data between customers

source/configuration/environments/generic/networking.rst
in this documentation section show how
Nic's can be optimize for productive environments
inspired by issue #282
=> documentation: NIC Offlaoding examples

requirements.txt
- Remove the versions in the requirements.txt to fix upcoming version issues
- This is partly: osism/issues#180
Signed-off-by: Ramona Rautenberg <rautenberg@osism.tech>
=> Deleted the pined versions for the documentation: documentation

source/configuration/environments/openstack/cinder.rst, source/configuration/environments/openstack/nova.rst, source/operations/openstack.rst
=> Documentation: Customer facing disk encryption how to enable it

source/operations/ceph.rst
=> Ceph: fix command line prompts

source/configuration/environments/openstack/neutron.rst
=> neutron availability zones

source/configuration/environments/custom.rst
partly: osism/issues#65
﻿Signed-off-by: Ramona Rautenberg <rautenberg@osism.tech>
=> change docker-compose to docker compose v2

source/development/ansible-style-guide.rst
- Add position for the when condition
- This closes #372
Signed-off-by: Ramona Rautenberg <rautenberg@osism.tech>
=> Ansible style guide: Position of when condition

source/test/benchmark/ceph.rst
Closes #396
Signed-off-by: Markus Lindenblatt <markus.lindenblatt@plusserver.com>
=> added fio sample for ceph benchmarking

source/operations.rst, source/operations/redis.rst
=> docu redis: fix aof file

source/development.rst, source/development/github.rst
=> added github guideline with first content beeing how to handle secrets in zuul

source/development/github.rst
=> development: add github issues

source/deployment/seed.rst
=> How to install sshpass on Macos

source/configuration/environments/infrastructure/nbde.rst
summary all steps in documentation to build, clean
and upload a luks cloud-image
=> add documentation for encrypted cloud image

source/configuration/environments/infrastructure/nbde.rst
on website indentation is not correct
=> Cosmetic Issue indentation

source/configuration/environments/infrastructure/nbde.rst
+virt-sysprep -a for file
-virt-sysprep -d for domain
=> virt-sysprep: command syntax

source/configuration/environments/infrastructure/nbde.rst
=> nbde: improve syntax

source/operations/cinder.rst, source/operations/docker.rst, source/operations/mariadb.rst, source/operations/placement.rst
=> operations: remove operations from the section title

source/operations/cinder.rst
=> operations/cinder: improve title

source/configuration/environments/ceph.rst, source/configuration/environments/custom.rst, source/configuration/environments/generic.rst, source/configuration/environments/infrastructure.rst, source/configuration/environments/manager.rst, source/configuration/environments/openstack.rst
=> configuration: improve titles of the environment sections

source/configuration/environments/custom.rst
=> Document how to use custom.* environmnets

source/configuration/environments.rst
=> configuration: sort list of environments

source/configuration/networks.rst
=> configuration/networks: smaller improvements

source/configuration/cookiecutter.rst
=> cookiecutter: improve titles

source/configuration/environments/openstack/neutron.rst
=> neutron: mention that DVR is not supported

source/upgrade/manager.rst
=> upgrade: improve manager

source/deployment/manager.rst
=> deployment: netbox is enabled by default

source/development/github.rst
Signed-off-by: Dr. Jens Harbott <harbott@osism.tech>
=> Development: Use PRs for GitHub

source/configuration/environments/openstack/nova.rst
how use flat file images in nova, reference to this SCS issue 
https://github.com/SovereignCloudStack/issues/issues/201
=> add local file storage

source/notes/openstack.rst
=> Add: Octavia feature matrix

source/deployment/bootstrap.rst, source/deployment/manager.rst, source/deployment/provisioning.rst, source/deployment/seed.rst
=> Tiny improvements in the Installation & Deployment chapter

source/deployment/bootstrap.rst, source/deployment/manager.rst, source/deployment/seed.rst
=> Tiny improvements in the Installation & Deployment chapter (pt. 2)

source/deployment/bootstrap.rst
=> Tiny improvements in the Installation & Deployment chapter (pt. 3)

source/deployment/seed.rst
Also adds example repository URLs.
=> seed: describe the configuration repository

source/services/haproxy.rst
add change certificate after train
https://github.com/osism/documentation/issues/443
=> Update documentation haproxy change certificate

source/deployment.rst, source/deployment/bootstrap.rst, source/deployment/manager.rst, source/deployment/provisioning.rst, source/deployment/seed.rst
=> Improve "Installation & Deployment" chapter

source/deployment/seed.rst
Part of osism/cfg-cookiecutter#417
=> seed: add a link to https://github.com/osism/cfg-cookiecutter

source/deployment/services/infrastructure.rst
=> Always deploy common

source/appendix.rst, source/appendix/references.rst
=> Add links to ansible collections documentation

source/configuration/environments/openstack.rst, source/configuration/environments/openstack/ceilometer.rst
Related to issue 271
https://github.com/SovereignCloudStack/issues/issues/271
=> adds Ceilometer section
