osism/documentation

source/configuration/initial-creation.rst

gilt overlay is called automatically by a hook script from cookiecutter now.

configuration/initial-creation: remove gilt overlay

---

source/configuration/networks.rst

I didn't read it carefully in the beginning and was a bit astonished why Ansible was complaining.

Fix typo prometheus_scraper_interface param

---

source/deployment/services/ceph.rst

- Remove bullets
- Define more precisly how to copy service keys
- Remove workaround notice

Rework deployment ceph chapter

---

source/operations/cinder.rst

operations/cinder: ImageBusy error raised while deleting rbd volume

---

source/operations/ceph.rst

operations/ceph: HEALTH_WARN application not enabled on 1 pool(s)

---

source/deployment/services/ceph.rst

there have to be a newline at the end of keyring file for commiting in repo, so openstack services, like glance and cinder, can communicate with ceph

added information about newline at the end of ceph keyring files

---

source/configuration/environments/openstack/neutron.rst

'neutron_external_interface' need to be set to network interface names not
bridge names.

Fix neutron external interface names

---

source/deployment/services/loadbalancer.rst

Kolla uses as default name `octavia_ssh_key`

Set Octavia ssh-key name to Kolla standard

---

README.md
source/conf.py
source/index.rst
source/overview/cli-reference.rst

Change docs.osism.de/io to docs.osism.tech

---

README.md
source/overview/cli-reference.rst

Use https://docs.osism.tech instead of http://docs.osism.tech

---

source/appendix/tables/webinterfaces.rst

Signed-off-by: Ferenc Géczi <geczi@univention.de>
* UMC Web is not meant to be used directly, external traffic should
go through UMC Gateway, as it handles error pages, security headers,
etc and optionally it can also act as a load balancer.
* UMC Gateway currently has two ports,
one intended for TLS and one non-TLS.

fix(umc): correct web interfaces

---

source/configuration/cookiecutter.rst

Use the requirements.txt file from cookiecutter repository, to install
the Python requirements.

Install cookiecutter requirements via URL

---

source/configuration/environments/generic/grub.rst

for Intel systems you will need:
- intel_iommu=on
- iommu=pt
for amd will need only:
- iommu=pt
because iommu is with amd_iommu already enabled by default
https://www.kernel.org/doc/html/v5.4/admin-guide/kernel-parameters.html
(5.4 it represent ubuntu focal 20.04, it latest it is the same)

documentation: grub cmdline iommu

---

source/development/ansible-style-guide.rst

- Add that tasks always must have names.
- This closes #371
Signed-off-by: Ramona Rautenberg <rautenberg@osism.tech>

Ansible style guide: Add that tasks always must have names

---

source/appendix.rst
source/appendix/configuartion.rst

it describe how fluentd is commuicate with elasticsearch authenticated
it was inspired by github issue:
https://github.com/osism/issues/issues/207
closes #207

fluentd authenticated communictaion

---

source/appendix/configuartion.rst

Fix two speliing issues  in appendix configuration.rst file

Fix two typos in appendix configuration.rst

---

source/development/opendev.rst

The code examples in the opendev development guide were not shown due to a missing colon.

fixed code examples not showing in development/opendev

---

source/notes/generic.rst

Closes osism/ansible-collection-commons#353

notes/docker-compose: error getting credentials

---

source/deployment/provisioning.rst

Use separate partition for /var/lib/ceph

---

source/overview/service-architecture.rst

add a section Linux Bridge and DVR is not supported

Add not supported Network Features

---

source/development/commit-messages.rst

Present tense for the header and DCO are important.
Signed-off-by: Dr. Jens Harbott <harbott@osism.tech>

Add more rules for commit messages

---

source/upgrade/kolla.rst

Old docker filter label "docker ps --filter=label=io.osism.openstack=queens" don't work.
I'll change this to "docker ps --filter=label=kolla_version=victoria"

Change filter label for "Remove old Docker images"

---

source/development/commit-messages.rst

- Replace sign-off-by
- Rework issue reference to full path reference
- Closes osism/documentation#407
Signed-off-by: Ramona Beermann <ramona.beermann@osism.tech>

Rework development guide

---

source/deployment/provisioning.rst
source/overview/requirements.rst

* We use Ubuntu 22.04 by default, accordingly use it everywhere
* Add note that the manual installation instructions are for Ubuntu 20.04 (will be revised soon).
* Remove everything to Preseed and only point to the osism/node-image repository
Closes osism/documentation#447

provisioning: use ubuntu 22.04 & remove pressed stuff

---

source/conf.py
test-requirements.txt

* RTD theme looks broken with Sphinx 6
* We use the Material theme in all other repositories with Sphinx

Change theme from rtd to material

---

source/deployment/bootstrap.rst
source/deployment/manager.rst
source/deployment/provisioning.rst

deployment: use osism instead of ubuntu as install user

---

source/overview/networks.rst

This is a leftover from Zabbix. The Prometheus and Netdata all run over the internal network.

Remove the monitoring network
